### PR TITLE
added handling of different cases for commands, refactored message pa…

### PR DESCRIPTION
**Pull request by smileyfist**
…rser into Utility class

---
This change is [Reviewable](https://reviewable.io/reviews/iag-nz/kudosplatform/36)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Just a couple of minor nitpicks :grin:

Again, you're kicking ass here pal!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[EchoBot/Utility.cs, line 77 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/36#-Kdm_x7ejyT7M5-xiCNV:-Kdm_x7gZ86k02MQGCSz:b-g0v9os) ([raw file](https://github.com/iag-nz/kudosplatform/blob/7b9cd4eb5d94341b4933dde6ea461090cd82200e/EchoBot/Utility.cs#L77)):*
> ```Smalltalk
>                 {
>                     //check if valid member
>                     bool validMember = validateMessageComponent(fullName, guildMembers);
> ```

Why assign to a variable if it is only used once? Why not:
```CSharp
if (validateMessageComponent(fullName, guildMembers))
```

---

*[EchoBot/Utility.cs, line 82 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/36#-Kdm_fuF1lkRwOIe29K7:-Kdm_fuG5NPIOKtmqfUF:bevkcd3) ([raw file](https://github.com/iag-nz/kudosplatform/blob/7b9cd4eb5d94341b4933dde6ea461090cd82200e/EchoBot/Utility.cs#L82)):*
> ```Smalltalk
>                     {
>                         //check if valid amount
>                         bool validAmount = validateMessageComponent(kudosAmountOrLastName, kudosAmounts);
> ```

Why assign to a variable if it is only used once? Why not:
```CSharp
if (validateMessageComponent(kudosAmountOrLastName, kudosAmounts))
```

---

*[EchoBot/Utility.cs, line 114 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/36#-Kdm_T8XIU8fZg627i7S:-Kdm_T8YNDQ2UZFNDVYj:bh4tpov) ([raw file](https://github.com/iag-nz/kudosplatform/blob/7b9cd4eb5d94341b4933dde6ea461090cd82200e/EchoBot/Utility.cs#L114)):*
> ```Smalltalk
>     }
> 
> }
> ```

Needs a CRLF at the end here :grin:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/36#-:-Kdma9BnWK04XnbYk_zF:bhactil)*

**Comment by smileyfist** [comment]
*[EchoBot/Utility.cs, line 114 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/36#-Kdm_T8XIU8fZg627i7S:-KdmtCitSTv_PFPlXmlk:byzzwxz) ([raw file](https://github.com/iag-nz/kudosplatform/blob/7b9cd4eb5d94341b4933dde6ea461090cd82200e/EchoBot/Utility.cs#L114)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Needs a CRLF at the end here :grin:
</blockquote></details>

how do i do this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/36)*

**Comment by smileyfist** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[EchoBot/Utility.cs, line 77 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/36#-Kdm_x7ejyT7M5-xiCNV:-KdmsL9D2ZDwZugx0RFP:b-cgdrag) ([raw file](https://github.com/iag-nz/kudosplatform/blob/7b9cd4eb5d94341b4933dde6ea461090cd82200e/EchoBot/Utility.cs#L77)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Why assign to a variable if it is only used once? Why not:
```CSharp
if (validateMessageComponent(fullName, guildMembers))
```
</blockquote></details>

good spotting, ill fix this now....

---

*[EchoBot/Utility.cs, line 82 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/36#-Kdm_fuF1lkRwOIe29K7:-KdmsOb7e7BkKfq_D3c5:b-cgdrag) ([raw file](https://github.com/iag-nz/kudosplatform/blob/7b9cd4eb5d94341b4933dde6ea461090cd82200e/EchoBot/Utility.cs#L82)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Why assign to a variable if it is only used once? Why not:
```CSharp
if (validateMessageComponent(kudosAmountOrLastName, kudosAmounts))
```
</blockquote></details>

good spotting, ill fix this now....

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/36)*

**Comment by smileyfist** [comment]
thanks for the thorough PR Dan :-)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/36#-:-KdmtJbct8bzcfE2l9cp:bgx0t6b)*

**Comment by PlagueHO** [comment]
Hehe - devs gotta keep other on their toes right? ;)

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[EchoBot/Utility.cs, line 114 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/36#-Kdm_T8XIU8fZg627i7S:-KdmuJSusL_EzgtzMbvZ:bmh42nb) ([raw file](https://github.com/iag-nz/kudosplatform/blob/7b9cd4eb5d94341b4933dde6ea461090cd82200e/EchoBot/Utility.cs#L114)):*
<details><summary><i>Previously, smileyfist (Reece Hewitt) wrote…</i></summary><blockquote>

how do i do this?
</blockquote></details>

Just add a line feed after the }

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/36#-:-KdmuM6ERMiWebD47aww:b-2ucxuj)*

**Comment by PlagueHO** [comment]
Reviewed 13 of 13 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[EchoBot/Web.config, line 12 at r3](https://reviewable.io:443/reviews/iag-nz/kudosplatform/36#-Kdn6-JlSNzZ5QWS1DQH:-Kdn6-JlSNzZ5QWS1DQI:bvdj03k) ([raw file](https://github.com/iag-nz/kudosplatform/blob/b2247cb0e2193928752fb34e3df70eaa058f5f76/EchoBot/Web.config#L12)):*
> ```XML
>     <add key="MicrosoftAppId" value="" />
>     <add key="MicrosoftAppPassword" value="" />
>     <add key="AzureTableName" value="DevGuild004" />
> ```

You should not do this! :) Once someone has your storage key they'll use it as a data dump site. I'll set up some safe deploy code for this once your PR is through.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/36)*

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 1 of 12 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/36#-:-KdnF9PRVJY7sEPuB1l7:bnfp4nl)*

**Pull request merged**
