### PR TITLE
Rework Azure Deploy and Build PSAKE Tasks to remove bugs

### PR DESCRIPTION
**Pull request by PlagueHO**
This change is [Reviewable](https://reviewable.io/reviews/iag-nz/kudosplatform/38)

### CODE REVIEW

**Comment by smileyfist** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[default.ps1, line 25 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38#-Kdn9xDSDdx8x9sFSlOZ:-Kdn9xDSDdx8x9sFSlO_:b-4hiba1) ([raw file](https://github.com/iag-nz/kudosplatform/blob/6478dd2755b504292864929146ecf5133f2a4503/default.ps1#L25)):*
> ```PowerShell
>       $azurePassword = ConvertTo-SecureString `
>         -String $ENV:azurePassword `
>         -AsPlainText `
> ```

password as plaintext ? or does this make it a secure string?

---

*[default.ps1, line 393 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38#-KdnAW-vV69XWV-AbN0B:-KdnAW-vV69XWV-AbN0C:bt8egy4) ([raw file](https://github.com/iag-nz/kudosplatform/blob/b7e3b0d78f2350ff2f881bc8699cada0f8ee794a/default.ps1#L393)):*
> ```PowerShell
>         -RoleDefinitionName Contributor `
>         -ServicePrincipalName $app.ApplicationId
>     } catch {
> ```

will this retry indefinitely?

---

*[README.md, line 85 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38#-KdnAg7SrkvhZTPi097f:-KdnAg7SrkvhZTPi097g:b-n7lqvj) ([raw file](https://github.com/iag-nz/kudosplatform/blob/b7e3b0d78f2350ff2f881bc8699cada0f8ee794a/README.md#L85)):*
> ```Markdown
>   -parameters @{ `
>     azureUSername = '03becdd7-3395-4bf2-8eff-528b7dcc9a07'
>     azurePassword ='P@ssword!1'
> ```

this looks suspect?

---

*[README.md, line 133 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38#-KdnAm1JTaQuQLjFD7ob:-KdnAm1JTaQuQLjFD7oc:b8qms59) ([raw file](https://github.com/iag-nz/kudosplatform/blob/b7e3b0d78f2350ff2f881bc8699cada0f8ee794a/README.md#L133)):*
> ```Markdown
>   -parameters @{ `
>     azureUSername = '03becdd7-3395-4bf2-8eff-528b7dcc9a07'
>     azurePassword ='P@ssword!1'
> ```

this looks suspect too?

---

*[EchoBot/Web.config, line 13 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38#-KdnAuDRmw22fnL4P9cM:-KdnAuDRmw22fnL4P9cN:b-tatmma) ([raw file](https://github.com/iag-nz/kudosplatform/blob/b7e3b0d78f2350ff2f881bc8699cada0f8ee794a/EchoBot/Web.config#L13)):*
> ```XML
>     <add key="MicrosoftAppPassword" value="" />
>     <add key="AzureTableName" value="Kudos" />
>     <add key="AzureResourceName" value="kptestplaguehosa" />
> ```

aaaah!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38)*

**Comment by smileyfist** [comment]
:lgtm: great work Dan! lots of good work

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38#-:-KdnB07r9skKqop9t_Eh:b-7jts2i)*

**Comment by smileyfist** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38#-:-KdnB5Oj4XPxNaMF9Wzt:bnfp4nl)*

**Comment by smileyfist** [comment]
*[default.ps1, line 25 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38#-Kdn9xDSDdx8x9sFSlOZ:-KdnB9PF63RuaUgH2-Ok:b2ni9ah) ([raw file](https://github.com/iag-nz/kudosplatform/blob/6478dd2755b504292864929146ecf5133f2a4503/default.ps1#L25)):*
<details><summary><i>Previously, smileyfist (Reece Hewitt) wrote…</i></summary><blockquote>

password as plaintext ? or does this make it a secure string?
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38)*

**Comment by smileyfist** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[README.md, line 85 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38#-KdnAg7SrkvhZTPi097f:-KdnBIUKGBRAawLGw3Do:bb7k0qh) ([raw file](https://github.com/iag-nz/kudosplatform/blob/b7e3b0d78f2350ff2f881bc8699cada0f8ee794a/README.md#L85)):*
<details><summary><i>Previously, smileyfist (Reece Hewitt) wrote…</i></summary><blockquote>

this looks suspect?
</blockquote></details>

lgtm

---

*[EchoBot/Web.config, line 13 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38#-KdnAuDRmw22fnL4P9cM:-KdnBKjulsz7AMV5z3jd:bb7k0qh) ([raw file](https://github.com/iag-nz/kudosplatform/blob/b7e3b0d78f2350ff2f881bc8699cada0f8ee794a/EchoBot/Web.config#L13)):*
<details><summary><i>Previously, smileyfist (Reece Hewitt) wrote…</i></summary><blockquote>

aaaah!
</blockquote></details>

lgtm

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38)*

**Comment by smileyfist** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38)*

**Comment by PlagueHO** [comment]
Hahaha you merged before I got a chance to submit a new PR to fix the comments :)

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[default.ps1, line 25 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38#-Kdn9xDSDdx8x9sFSlOZ:-KdnBo0wEmgTU0fIevQe:bliwb7) ([raw file](https://github.com/iag-nz/kudosplatform/blob/6478dd2755b504292864929146ecf5133f2a4503/default.ps1#L25)):*
<details><summary><i>Previously, smileyfist (Reece Hewitt) wrote…</i></summary><blockquote>

ok
</blockquote></details>

This makes it a SecureString - although it will still exist as plaintext if you've passed it in that way - better to pass a cred object.

---

*[default.ps1, line 393 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38#-KdnAW-vV69XWV-AbN0B:-KdnC-ndIiTupKytD45i:bu93zvo) ([raw file](https://github.com/iag-nz/kudosplatform/blob/b7e3b0d78f2350ff2f881bc8699cada0f8ee794a/default.ps1#L393)):*
<details><summary><i>Previously, smileyfist (Reece Hewitt) wrote…</i></summary><blockquote>

will this retry indefinitely?
</blockquote></details>

Yes it will. And that is a good catch. Fixed.

---

*[README.md, line 85 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38#-KdnAg7SrkvhZTPi097f:-KdnCqqSo8F6-6NPqHTn:bhwk5gp) ([raw file](https://github.com/iag-nz/kudosplatform/blob/b7e3b0d78f2350ff2f881bc8699cada0f8ee794a/README.md#L85)):*
<details><summary><i>Previously, smileyfist (Reece Hewitt) wrote…</i></summary><blockquote>

lgtm
</blockquote></details>

It isn't real :grin: It's an example. But if it was used for real it would be suspect.

---

*[README.md, line 133 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38#-KdnAm1JTaQuQLjFD7ob:-KdnD17WqccPKPFKacMY:b-89a4l7) ([raw file](https://github.com/iag-nz/kudosplatform/blob/b7e3b0d78f2350ff2f881bc8699cada0f8ee794a/README.md#L133)):*
<details><summary><i>Previously, smileyfist (Reece Hewitt) wrote…</i></summary><blockquote>

this looks suspect too?
</blockquote></details>

Ditto

---

*[EchoBot/Web.config, line 13 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38#-KdnAuDRmw22fnL4P9cM:-KdnD7JHDIwCU6cOPqAW:b-vocuhk) ([raw file](https://github.com/iag-nz/kudosplatform/blob/b7e3b0d78f2350ff2f881bc8699cada0f8ee794a/EchoBot/Web.config#L13)):*
<details><summary><i>Previously, smileyfist (Reece Hewitt) wrote…</i></summary><blockquote>

lgtm
</blockquote></details>

Ahahaha Shit! :grin:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38#-:-KdnDZjRpY0owkoW6Xpf:byj36ye)*

**Comment by PlagueHO** [comment]
I mean a new commit - not PR

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38#-:-KdnDg48K4sf5NwhpCri:b76cm7h)*

**Comment by smileyfist** [comment]
lol! 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/38#-:-KdnDqdkWf4NnCHtrQWG:b-7n6qwt)*

**Pull request merged**
