### PR TITLE
removed json, added Azure table storage. still needs work, but should enable it to be deployed etc..

### PR DESCRIPTION
**Pull request by smileyfist**
This change is [Reviewable](https://reviewable.io/reviews/iag-nz/kudosplatform/32)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Reviewed 21 of 22 files at r1.
Review status: 21 of 22 files reviewed at latest revision, 11 unresolved discussions.

---

*[EchoBot/ShouldBeRestAPI.cs, line 10 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFhwAmaIs09NKqvBnG:-KcFhwAmaIs09NKqvBnH:b1i6jdl) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/ShouldBeRestAPI.cs#L10)):*
> ```Smalltalk
> namespace EchoBot
> {
>     public class ShouldBeRestAPI
> ```

Heh - nice name ;) Guessing this is not final name? 

---

*[EchoBot/ShouldBeRestAPI.cs, line 18 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFi-h3e6QSyLNZcq06:-KcFi-h3e6QSyLNZcq07:b-klkv2l) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/ShouldBeRestAPI.cs#L18)):*
> ```Smalltalk
> 
>         //TODO access Azure via REST API. this will do for now...
>         public ShouldBeRestAPI()
> ```

Not final name right? :)

---

*[EchoBot/ShouldBeRestAPI.cs, line 22 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFhYHZ1VzGTUqiNAAH:-KcFhYH_WVvQ4sggHA3U:b4rgt9v) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/ShouldBeRestAPI.cs#L22)):*
> ```Smalltalk
>             //TODO don't store creds here
>             tableName = "DevGuild001";
>             myCreds = new StorageCredentials("kudosreece", "NCYwuqBhibQhF57pXG4by1gasMsoUUewaIa102Ck8Ztc5nnaJoWFkUDE4Ph8VCcCA9cK8tTOb13iymr4+xPHzQ==");
> ```

Haha ok. Just to check, but these aren't real creds right - because there are constant GitHub scrapers that will nab your creds. :) But once you've moved them into Web.config or some other file, I'll put some work into configuring everything during deployment.

---

*[EchoBot/Controllers/MessagesController.cs, line 106 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFiNpuAkUTfCJF3fVt:-KcFiNpuAkUTfCJF3fVu:b5tfe7y) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/Controllers/MessagesController.cs#L106)):*
> ```Smalltalk
> 
> 
>         private void PrepareDataStorage()
> ```

I'm thinking we need to move this code completely out into the deployment code. E.g. these are test harness values and you wouldn't want them in. But we can do this later on. Someone can create an issue and do a PR.

---

*[EchoBot/Controllers/MessagesController.cs, line 151 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFih4PJUJ5y25bk3LL:-KcFih4PJUJ5y25bk3LM:bri7ju1) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/Controllers/MessagesController.cs#L151)):*
> ```Smalltalk
> 
> 
> //string targetMember = string.Empty;
> ```

Remove all commented out code :grin: That is not a recommended practice. It's OK when working on your own fork, but PR's shouldn't include code that has been commented.

---

*[EchoBot/EchoBot/kudosData.json, line 15 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFj5tNL6iPjMkyw7Mj:-KcFj5tNL6iPjMkyw7Mk:b-jpw2ii) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/EchoBot/kudosData.json#L15)):*
> ```JSON
>     "dan": 33.0
>   }
> }
> ```

Needs CRLF here please :)

---

*[EchoBot/EchoBot/packages.config, line 15 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFjA4orTuKhKhKyQ-F:-KcFjA4orTuKhKhKyQ-G:b-cql33o) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/EchoBot/packages.config#L15)):*
> ```XML
>   <package id="Newtonsoft.Json" version="8.0.3" targetFramework="net46" />
>   <package id="System.IdentityModel.Tokens.Jwt" version="4.0.2.206221351" targetFramework="net46" />
> </packages>
> ```

CRLF here plesae

---

*[EchoBot/EchoBot/Web.config, line 68 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFjDuKrrythad3WNFa:-KcFjDuKrrythad3WNFb:bva7jaa) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/EchoBot/Web.config#L68)):*
> ```XML
>     </assemblyBinding>
>   </runtime>
> </configuration>
> ```

CRLF here please

---

*[EchoBot/EchoBot/Web.Debug.config, line 30 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFjFrJ0mgOVXcvcKOx:-KcFjFrJ0mgOVXcvcKOy:brj242r) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/EchoBot/Web.Debug.config#L30)):*
> ```XML
>     -->
>   </system.web>
> </configuration>
> ```

CRLF Here please :)

---

*[EchoBot/EchoBot/Web.Release.config, line 31 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFjHsQcgXDScGaBQlz:-KcFjHsROqGUmxPTlrxh:b-oarv15) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/EchoBot/Web.Release.config#L31)):*
> ```XML
>     -->
>   </system.web>
> </configuration>
> ```

Yep - CRLF Here too

---

*[EchoBot/EchoBot/Controllers/MessagesController.cs, line 225 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFjP1Pf9F0-MGmQRAt:-KcFjP1Pf9F0-MGmQRAu:byfz8h1) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/EchoBot/Controllers/MessagesController.cs#L225)):*
> ```Smalltalk
>         }
>     }
> }
> ```

CRLF please!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32)*

**Comment by PlagueHO** [comment]
Nice job @smileyfist ! Way to go! :grin: Sorry about the nitpicks - I've just been hammered by the MSFT team for some of my own PR's so I must just be getting my own back on you :laughing: 

---

Reviewed 1 of 22 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-:-KcFjYvy2c-SWpqb8O8Z:b-a2hwcr)*

**Comment by smileyfist** [comment]
*[EchoBot/ShouldBeRestAPI.cs, line 10 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFhwAmaIs09NKqvBnG:-KcFqkJuBzN2cIY3cYxI:bx7kv86) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/ShouldBeRestAPI.cs#L10)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Heh - nice name ;) Guessing this is not final name? 
</blockquote></details>

:) correct. I imagine we'll kill this when we have Rest API. though for the immediate short term it plugs the bot to Azure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32)*

**Comment by smileyfist** [comment]
*[EchoBot/ShouldBeRestAPI.cs, line 18 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFi-h3e6QSyLNZcq06:-KcFr04_7Wq66LlneM7S:btzxu8p) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/ShouldBeRestAPI.cs#L18)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Not final name right? :)
</blockquote></details>

correct. not final name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32)*

**Comment by smileyfist** [comment]
*[EchoBot/ShouldBeRestAPI.cs, line 22 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFhYHZ1VzGTUqiNAAH:-KcFr3-A83ne7-Xz_tlM:b-pp0a1d) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/ShouldBeRestAPI.cs#L22)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Haha ok. Just to check, but these aren't real creds right - because there are constant GitHub scrapers that will nab your creds. :) But once you've moved them into Web.config or some other file, I'll put some work into configuring everything during deployment.
</blockquote></details>

thanks for this. I knew this wouldn't be a long term solution but i see its a poor temporary one too. I'll rework this...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32)*

**Comment by smileyfist** [comment]
*[EchoBot/Controllers/MessagesController.cs, line 106 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFiNpuAkUTfCJF3fVt:-KcFrL95P4SzdTBvKqfD:b-3ur399) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/Controllers/MessagesController.cs#L106)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I'm thinking we need to move this code completely out into the deployment code. E.g. these are test harness values and you wouldn't want them in. But we can do this later on. Someone can create an issue and do a PR.
</blockquote></details>

yeah, i think this will dissappear when we have a REST api later on..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32)*

**Comment by smileyfist** [comment]
*[EchoBot/Controllers/MessagesController.cs, line 151 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFih4PJUJ5y25bk3LL:-KcFrTp-LqcvMY27ZSkM:bxs5k67) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/Controllers/MessagesController.cs#L151)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Remove all commented out code :grin: That is not a recommended practice. It's OK when working on your own fork, but PR's shouldn't include code that has been commented.
</blockquote></details>

good point. thanks. i'll fix this up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32)*

**Comment by smileyfist** [comment]
*[EchoBot/EchoBot/kudosData.json, line 15 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFj5tNL6iPjMkyw7Mj:-KcFrbR6DrKLph4_gSSC:btqqvlr) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/EchoBot/kudosData.json#L15)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Needs CRLF here please :)
</blockquote></details>

I'll kill this file with fire as it wont be needed anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32)*

**Comment by smileyfist** [comment]
*[EchoBot/EchoBot/packages.config, line 15 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFjA4orTuKhKhKyQ-F:-KcFrlYP6U8Cj4XRGeP1:bn92ua4) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/EchoBot/packages.config#L15)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

CRLF here plesae
</blockquote></details>

i have hopefully added this now...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32)*

**Comment by smileyfist** [comment]
*[EchoBot/EchoBot/Web.config, line 68 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFjDuKrrythad3WNFa:-KcFrrFUR9JIK2fDkBMq:b-px3hxc) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/EchoBot/Web.config#L68)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

CRLF here please
</blockquote></details>

i have hopefully fixed this now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32)*

**Comment by smileyfist** [comment]
Thanks @PlagueHO for the thorough review! valid points made. I'm amending now..

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-:-KcFt6xd6MxI7MyoO9VZ:b-o12u00)*

**Comment by PlagueHO** [comment]
:lgtm: Few nitpicks, but nothing I'll hold you up on cause you've done a bloody great job :smile: 

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[EchoBot/ShouldBeRestAPI.cs, line 22 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFhYHZ1VzGTUqiNAAH:-KcG3gqQkZG77BV8xd1X:bptyaqw) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/ShouldBeRestAPI.cs#L22)):*
<details><summary><i>Previously, smileyfist (Reece Hewitt) wrote…</i></summary><blockquote>

thanks for this. I knew this wouldn't be a long term solution but i see its a poor temporary one too. I'll rework this...
</blockquote></details>

Good work pal :LGTM:

---

*[EchoBot/EchoBot/packages.config, line 15 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFjA4orTuKhKhKyQ-F:-KcG3sJncwvOHDRlhb2R:b-m8phyw) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/EchoBot/packages.config#L15)):*
<details><summary><i>Previously, smileyfist (Reece Hewitt) wrote…</i></summary><blockquote>

i have hopefully added this now...
</blockquote></details>

Still missing :( But that could be because VS. So we'll just ignore it for now :)

---

*[EchoBot/EchoBot/Web.config, line 68 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFjDuKrrythad3WNFa:-KcG3yhdAS3K_ZTzX4xM:b-aeaksc) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/EchoBot/Web.config#L68)):*
<details><summary><i>Previously, smileyfist (Reece Hewitt) wrote…</i></summary><blockquote>

i have hopefully fixed this now.
</blockquote></details>

Nup! Still there but will ignore.

---

*[EchoBot/EchoBot/Web.Debug.config, line 30 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFjFrJ0mgOVXcvcKOx:-KcG46XEe-Pm5x4wDvVB:bjw1nd) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/EchoBot/Web.Debug.config#L30)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

CRLF Here please :)
</blockquote></details>

:LGTM:

---

*[EchoBot/EchoBot/Controllers/MessagesController.cs, line 225 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-KcFjP1Pf9F0-MGmQRAt:-KcG4C6jr5Y3ykZvrhfu:b-50mzi0) ([raw file](https://github.com/iag-nz/kudosplatform/blob/564a3e90dc1b635b6107f83ec38c9b242b6b77fb/EchoBot/EchoBot/Controllers/MessagesController.cs#L225)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

CRLF please!
</blockquote></details>

Still there but will ignore for now :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/32#-:-KcG4FSKxXaeU7PfEPc-:b-c654ia)*

**Pull request merged**
