### PR TITLE
Added EchoBot Project - Fixes #19

### LINKED ISSUE #19: Create EchoBot Project in KudosPlatform Solution
This will query the KudosPlatformDataStore REST API end point (not written yet) to retrieve current information about the Kudos assigned to Users.

### PR DESCRIPTION
**Pull request by smileyfist**
Hi all, so I've converted the Kudos part of the Slackbot I made into a Microsoft Bot Framework template. Currently it is able to be used with the emulator to do the following: "list" => bot replies with all Kudos, "dan 5" => adds 5 kudos to dan and bot replies with updated Kudos. + various error handling messages. Note this is very much a first cut, with probably numerous flaws and needed improvements missing. But i figured we gotta start somewhere right?

…a Microsoft Bot Framework template. Currently it is able to be used with the emulator to do the following: "list" => bot replies with all Kudos, "dan 5" => adds 5 kudos to dan and bot replies  with updated Kudos. + various error handling messages. Note this is very much a first cut, with probably numerous flaws and needed improvements missing. But i figured we gotta start somewhere right?

---
This change is [Reviewable](https://reviewable.io/reviews/iag-nz/kudosplatform/18)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@smileyfist - bro! You're a legend! That is some awesome stuff!

Couple of questions:
1. Is it possible to move the EchoBot project into the KudosPlatform solution? It makes deploying with ARM much easier with a single solution. It also makes it much more logical.
2. Is the thinking to eventually replace the KudosData.json file with an Azure Table? Otherwise the platform isn't stateless and deploying would wipe out the data. Happy to use this as a placeholder for now though.
3. This would be deployed to an Azure Web Site (PaaS) - do you think this would work deployed like that?

But again, that is awesome!

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[EchoBot/EchoBot/kudosData.json, line 15 at r1](https://reviewable.io:443/reviews/iag-nz/kudosplatform/18#-K_7qTt6MCA4Lij1ImAI:-K_7qTt6MCA4Lij1ImAJ:b-2qnvrz) ([raw file](https://github.com/iag-nz/kudosplatform/blob/ae6eefed3cc582ba168353e1ddbe3d162bb98e57/EchoBot/EchoBot/kudosData.json#L15)):*
> ```JSON
>     "dan": 33.0
>   }
> }
> ```

Add a CRLF here please :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/18#-:-K_7pgQ0B_Y79m3tMgSp:b55cj2n)*

**Comment by PlagueHO** [comment]
Hi @smileyfist - I created an issue (AKA a story) for this change and assigned you to it :grin: (e.g. welcome to the big bad world of OSS dev). I also edited your PR so that it is readable now too :1st_place_medal: 

I had a thought - to stick with the microservice design patterns of this project, could you rather than read the JSON from a file, query a REST end point for the Kudos data JSON? I could easily put together a REST API (using an Azure Function) that returns your test data. That way your bot is still stateless and doesn't need to be redeployed to update the data. Would that work?

**Comment by smileyfist** [comment]
Hi @PlagueHO,
Cheers, yes using the json file is just a temporary fix.

Your ideas of using Azure table and PaaS sound good to me, though I havn't used them myself before.
I'll throw some more effort into fixes if/when I get a chance.

I'll have a chat with you when I get into work, as I don't seems to be able to access the issues board?

Cheers
Reece

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/kudosplatform/18#-:-K_BnuvNAIUYt-6YQcG0:b-7nxp95)*

**Comment by PlagueHO** [comment]
@smileyfist - I did a presentation on using Azure Functions for Serverless REST API front ends for data stores the other other day for the Dev Guild....but that's right...you were skiving off on holiday or something. :grin:

But you'd have no trouble with functions or Azure Table (or AWS Table) stores - it's easier than the Bot framework - so you'd find it trivial. I plan to put together something over the next couple of days - you'll be able to take a dig about it in then.

**Comment by PlagueHO** [comment]
@smileyfist merged to origin. OOPS! :cry: ♿️

**Pull request closed without merging**
